"""Client interfaces.

The pipelines depend only on these Protocols. Production code injects the
HTTP clients; the test harness injects in-memory fakes. This keeps the
approval gate testable end-to-end without touching live systems.
"""
from __future__ import annotations

from typing import Any, Protocol


class ZohoClient(Protocol):
    def upsert_account(self, account: dict[str, Any]) -> str: ...
    def get_account(self, account_id: str) -> dict[str, Any] | None: ...
    def find_account_by_domain(self, domain: str) -> dict[str, Any] | None: ...
    def upsert_contact(self, contact: dict[str, Any]) -> str: ...
    def get_contact(self, contact_id: str) -> dict[str, Any] | None: ...
    def find_contact_by_email(self, email: str) -> dict[str, Any] | None: ...
    def update_contact(self, contact_id: str, fields: dict[str, Any]) -> None: ...
    def update_account(self, account_id: str, fields: dict[str, Any]) -> None: ...
    def delete_records(self, module: str, ids: list[str]) -> None: ...
    def list_accounts(self, fields: list[str]) -> list[dict[str, Any]]: ...
    def list_contacts(self, fields: list[str]) -> list[dict[str, Any]]: ...


class ApolloClient(Protocol):
    def search_people(
        self, *, domain: str, titles: list[str], seniorities: list[str], limit: int
    ) -> list[dict[str, Any]]: ...


class ClayClient(Protocol):
    def enqueue_contact(self, payload: dict[str, Any]) -> str: ...


class SmartleadClient(Protocol):
    def find_lead_by_email(self, campaign_id: str, email: str) -> dict[str, Any] | None: ...
    def add_lead(self, campaign_id: str, lead: dict[str, Any]) -> str: ...
